### ISSUE TITLE
Player cant pickup items

### ISSUE THREAD

**Issue by SATIVACHEATS1** [badewen/Growtopia-Multibot#8]
The player cant pick up items/gems or go through portals is there any way of disabling this?

**Comment by badewen** [comment]
Unfortunately, there is no way to disable it since this is the intended behavior. The bot works just like Lucifer bots. It wont collect anything or go through portal unless it was explicitly told to using script.

**Comment by SATIVACHEATS1** [comment]
Okay thx for the response what would a script that collects items where the player is standing look like

**Comment by badewen** [comment]
Hmm idk currently. The executor doesnt have any api to get any dropped item as of now
